import {
  LayoutDashboard, BookOpen, Users, BookPlus, RotateCcw, AlertTriangle,
  Settings, Home, Library, History, User, ScanBarcode, Brain,
  Camera, Calculator, Wand2, Upload, BarChart3, Bell, FileText, MapPin,
  Sparkles, Mic, Target, Bot, Star, Heart, QrCode, TrendingUp, BellRing, FileSearch, ShieldCheck,
} from 'lucide-react';

export const adminLinks = [
  { to: '/admin', label: 'Dashboard', icon: LayoutDashboard },
  { to: '/admin/books', label: 'Books', icon: BookOpen },
  { to: '/admin/members', label: 'Members', icon: Users },
  { to: '/admin/issue', label: 'Issue Book', icon: BookPlus },
  { to: '/admin/return', label: 'Return Book', icon: RotateCcw },
  { to: '/admin/overdue', label: 'Overdue', icon: AlertTriangle },
  { to: '/admin/scanner', label: 'Barcode Scanner', icon: ScanBarcode },
  { to: '/admin/analytics', label: 'AI Analytics', icon: Brain },
  { to: '/admin/damage', label: 'Damage Detection', icon: Camera },
  { to: '/admin/fines', label: 'Fine Calculator', icon: Calculator },
  { to: '/admin/cataloging', label: 'AI Cataloging', icon: Wand2 },
  { to: '/admin/import', label: 'Bulk Import/Export', icon: Upload },
  { to: '/admin/student-analytics', label: 'Student Analytics', icon: BarChart3 },
  { to: '/admin/notifications', label: 'Notifications', icon: Bell },
  { to: '/admin/reports', label: 'AI Reports', icon: FileText },
  { to: '/admin/shelves', label: 'Shelf Management', icon: MapPin },
  { to: '/admin/predictive-availability', label: 'Predictive Availability', icon: TrendingUp },
  { to: '/admin/audit', label: 'AI Audit Trail', icon: ShieldCheck },
  { to: '/admin/settings', label: 'Settings', icon: Settings },
];

export const studentLinks = [
  { to: '/student', label: 'Home', icon: Home },
  { to: '/student/books', label: 'Browse Books', icon: BookOpen },
  { to: '/student/mybooks', label: 'My Books', icon: Library },
  { to: '/student/history', label: 'History', icon: History },
  { to: '/student/recommendations', label: 'AI Recommendations', icon: Sparkles },
  { to: '/student/voice-search', label: 'Voice Search', icon: Mic },
  { to: '/student/goals', label: 'Reading Goals', icon: Target },
  { to: '/student/companion', label: 'AI Study Companion', icon: Bot },
  { to: '/student/reviews', label: 'Book Reviews', icon: Star },
  { to: '/student/wishlist', label: 'Wishlist', icon: Heart },
  { to: '/student/qr-borrow', label: 'QR Borrow', icon: QrCode },
  { to: '/student/stats', label: 'Reading Stats', icon: TrendingUp },
  { to: '/student/alerts', label: 'Availability Alerts', icon: BellRing },
  { to: '/student/ai-summary', label: 'AI Summary', icon: FileSearch },
  { to: '/student/profile', label: 'Profile', icon: User },
];
